### PR TITLE
Fixed an issue #97 with empty array

### PR DESCRIPTION
**Pull request by INaleva**
The issue is that the bot trying to get order data from the exchange servers, but this might take up to 9 seconds to respond with an answer.

Best approach is to retry until the first item of the array exists.

### CODE REVIEW

**Comment by fj317** [comment]
Nice fix. As you mentioned it could take up to 9 seconds which is a problem in a pump & dump, but I think people would rather the bot work & wait a bit than it crash & fail.
Adding to the code base.

**Comment by INaleva** [comment]
@fj317 Yes, your approach is still not the best there is.
I've been working for about 1 month now on a bot of my own.
As for now, it detects the coin within 0.1 - 0.3 second, and then opens a sell order within 0.31-0.55 second.

**Comment by rayures** [comment]
for some reason this did not work on my bot, error-ed

````2021-05-03 11:28:10.568959 Processing sell order.
Traceback (most recent call last):
  File "PumpBot.py", line 333, in <module>
    while not 0 < len(coinOrderInfo['items']):
KeyError: 'items'
````

so i implemented this, and so far it works: 

````while True: 
    try:
       coinOrderInfo = order["fills"][0] 
    except:
        #retry
        print('no buy order info available, retrying...')
        continue
    else:
        #continue with script
        print('got buy info, continue')
        break
````

**Comment by fj317** [comment]
I've pushed my own fix to the bot now that should fix this empty array issue.

**Pull request merged**
